//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIFI.Buchandlung.Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LetzterSprachcode {
            get {
                return ((string)(this["LetzterSprachcode"]));
            }
            set {
                this["LetzterSprachcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BeimBeendenFragen {
            get {
                return ((bool)(this["BeimBeendenFragen"]));
            }
            set {
                this["BeimBeendenFragen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=(localdb)\\mssqllocaldb;AttachDbFilename=..\\..\\..\\..\\WIFI.Buchandlung.Clien" +
            "t\\Datenbank\\WIFIBuchhaltung.mdf;Database=WIFIBuchhaltung;Trusted_Connection=Yes;" +
            "")]
        public string Verbindungszeichenfolge {
            get {
                return ((string)(this["Verbindungszeichenfolge"]));
            }
            set {
                this["Verbindungszeichenfolge"] = value;
            }
        }
    }
}
